#!/usr/bin/env bash
# SSH client configuration

Host *
	PaswwordAuthentication no
	IdentiyFile ~/.ssh/school
	SendEnv LANG LC_*
	HashKnownHosts yes
	GSSAPIAuthentication yes
	GSSAPIDeleqgateCredentials no

